id: IB7208724
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-06-29T16:12:09.798164'
last_modified: '2022-06-29T16:12:09.798178'
parser: null
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: sa
  base:
    6833:
      base_file: 6833.txt
      order: 1
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
